# Generated by Django 2.0.4 on 2018-09-29 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eLearning', '0002_auto_20180926_2144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_name', models.CharField(max_length=200, verbose_name='Asignación')),
                ('assignament_description', models.CharField(max_length=1000, verbose_name='Descripción de la Asignación')),
                ('spec_document_url', models.URLField(max_length=1000, verbose_name='Documento Adjunto')),
                ('deadline_date', models.DateTimeField(verbose_name='Fecha de Entrega')),
                ('pub_date', models.DateTimeField(verbose_name='Fecha de Publicación')),
                ('is_active', models.BooleanField(verbose_name='Activo')),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(max_length=200, verbose_name='Nombre del Curso'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eLearning.Course'),
        ),
    ]
