# Generated by Django 2.0.4 on 2018-09-29 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eLearning', '0003_auto_20180929_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='assignment_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Tarea'), (2, 'Trabajo en Grupo'), (3, 'Examen')], default=1, verbose_name='Tipo de Asignación'),
            preserve_default=False,
        ),
    ]
